### ISSUE TITLE
The popup appears from the bottom right

### ISSUE THREAD

**Issue by el3ankaboot** [exyte/PopupView#136]
Hello there,

I have an issue with V2.6.0, the popup always appears from the bottom right of the screen no matter what parameter I pass to .appearFrom
The parameter passed differs in the disappear
So for example if I added .apearFrom(.top), The popup will appear from the bottom right and disappear from the top.

**Comment by f3dm76** [comment]
Hey @el3ankaboot, could you please specify you xcode version, ios version and attach your compilable, reproducible example? Have a nice day!

**Comment by el3ankaboot** [comment]
Hi @f3dm76 , Thanks for your quick response.

Xcode version : 14.2
iOS Version: tried running on 16.2 and 16.0.2
Platform: iPhone

This is my code :

```
        .popup(isPresented: $viewModel.showDeleteConfirmationPopup) {
            
            DeleteFeedItemPopupView(viewModel: viewModel.deleteFeedItemPopupViewModel)
        } customize: {
            $0
                .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                .position(.center)
                .closeOnTap(false)
                .closeOnTapOutside(true)
                .backgroundColor(.black.opacity(0.4))
        }
```

Where 'DeleteFeedItemPopupView' is just a customized alert view.

**Comment by f3dm76** [comment]
Many thanks @el3ankaboot, I'll give a look as soon as I can

**Comment by f3dm76** [comment]
Hey @el3ankaboot, here is what I'm getting on xcode 14.3.1 (I hope it's close enough), ios 16.2, iphone 14 pro. I added the second popup as you specified:

https://github.com/exyte/PopupView/assets/9447630/a47697f4-b798-44e8-af46-33a23c6eb374

Here is the full code:
```
struct ContentView: View {

    @State var isPresented1 = false
    @State var isPresented2 = false

    var body: some View {
        VStack {
            Button("First") {
                isPresented1 = true
            }
            Button("Second") {
                isPresented2 = true
            }
        }
        .popup(isPresented: $isPresented1) {
            Color.blue.frame(width: 100, height: 100)
        } customize: {
            $0
                .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                .position(.bottomTrailing)
                .closeOnTap(false)
                .closeOnTapOutside(true)
                .backgroundColor(.black.opacity(0.4))
        }
        .popup(isPresented: $isPresented2) {
            Color.pink.frame(width: 100, height: 100)
        } customize: {
            $0
                .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                .position(.center)
                .closeOnTap(false)
                .closeOnTapOutside(true)
                .backgroundColor(.black.opacity(0.4))
        }
    }
}
```

Could you please provide the whole code needed to reproduce? Please make sure the issue reproduces on the isolated piece of code you provide. Have a nice day

**Comment by nathan995** [comment]
Hey @f3dm76, for me the issue occurs when I use `.popup` with `.fullScreenCover`. When I dismiss `.fullScreenCover` it slides down to bottom by default and when I display `.popup` afterwards it to appears from bottom right corner.

A workaround I found is setting `UIView.setAnimationsEnabled(false)` before dismissing `.fullScreenCover` and enabling again. Seems like the slide down animation of fullScreenCover is affecting popup.

**Comment by el3ankaboot** [comment]
Hi @f3dm76,

I added a small edit on your code to show what I meant.

`struct ContentView: View {

    @State var isPresented1 = false
    @State var isPresented2 = false

    var body: some View {
        VStack {
            Button("First") {
                isPresented1 = true
            }
           
        }
        .popup(isPresented: $isPresented1) {
            ZStack {
                Color.blue.frame(width: 100, height: 100)
                Button("Second") {
                    isPresented1 = false
                    isPresented2 = true
                }
            }
           
        } customize: {
            $0
                .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                .position(.bottomTrailing)
                .closeOnTap(false)
                .closeOnTapOutside(true)
                .backgroundColor(.black.opacity(0.4))
        }
        .popup(isPresented: $isPresented2) {
            Color.pink.frame(width: 100, height: 100)
        } customize: {
            $0
                .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                .position(.center)
                .closeOnTap(false)
                .closeOnTapOutside(true)
                .backgroundColor(.black.opacity(0.4))
        }
    }
}
`

**Comment by mackbex** [comment]
i'm using this library with SwiftUI that in my case, this popup appears from bottom right reproduced when i use @Envronment openURL in body. 
workaround solution was just use another function to open url (like UIApplication.shared.open or use Link)
fyi @f3dm76

**Comment by osmanmesutozcan** [comment]
I have a similar issue as well.

If I chain multiple popups, first popup opens normally. The following popup will appear from right bottom.

That's said, my popups always open in the same order, so if I start showing popups bottom up, it works normally.

E.g. this works
```
        // This shows after
        .popup(isPresented: $showScanSheet) { scanPhotosPopup } customize: { params in
            floaterModifier(params: params)
                .closeOnTap(false)
        }

        // This shows first
        .popup(isPresented: $showAddSheet) { scanOptionsPopup } customize: { params in
            floaterModifier(params: params)
                .closeOnTap(true)
        }
```

E.g. enters from right bottom
```
        // This shows first
        .popup(isPresented: $showAddSheet) { scanOptionsPopup } customize: { params in
            floaterModifier(params: params)
                .closeOnTap(true)
        }
        
        // This shows after
        .popup(isPresented: $showScanSheet) { scanPhotosPopup } customize: { params in
            floaterModifier(params: params)
                .closeOnTap(false)
        }
```

**Comment by f3dm76** [comment]
Hey everyone, I think I fixed it, could you please check out version 2.6.2? Have a wanderfull day, guys!

**Comment by Muhammadbarznji** [comment]
Hi @f3dm76, I did try version 2.6.2 but it still appears at the bottom right corner.

**Comment by f3dm76** [comment]
Hey @osmanmesutozcan, thank you for the explanations, but I need to know exactly how the second popup is triggered. When exactly is showScanSheet set to true? Please provide full example, so I can launch and reproduce the issue.
Here is my code, the declaration order changes nothing, and it works correctly.

```
struct ContentView: View {

    @State var isPresented1 = false
    @State var isPresented2 = false

    var body: some View {
        VStack {
            Button("First") {
                isPresented1 = true
            }
        }

        .popup(isPresented: $isPresented1) {
            ZStack {
                Color.black.frame(width: 100, height: 100)
                Button("Second") {
                    isPresented1 = false
                    isPresented2 = true
                }
            }
        } customize: {
            $0
                .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                .position(.bottomLeading)
                .isOpaque(false)
                .closeOnTap(false)
                .closeOnTapOutside(true)
                .backgroundColor(.black.opacity(0.4))
        }

        .popup(isPresented: $isPresented2) {
            Color.pink.frame(width: 100, height: 100)
        } customize: {
            $0
                .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                .position(.center)
                .closeOnTap(false)
                .closeOnTapOutside(true)
                .backgroundColor(.black.opacity(0.4))
        }
    }
}
```

**Comment by nathan995** [comment]
I think the issue is caused by first popup not being removed completely before second popup shows. I got it working correctly by delaying second popup.
```
DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
      showSecondToast = true
}
```

**Comment by f3dm76** [comment]
Hey guys, it's been a while., so I'm closing this one for now. Please feel free to reopen with some reproduction code
