### ISSUE TITLE
Popup view makes the child view navigate to top

### ISSUE THREAD

**Issue by solkpolk** [exyte/PopupView#53]
Xcode. 13.1
iOS 15.0

At the end of a long list I want to trigger a popup view. When the user triggers it the scrollview is reset to beginning. 

```
struct ChildView: View {
    
    @Binding var show: Bool
    let text: String
    
    var body: some View {
        
        ScrollView(.vertical, showsIndicators: false) {
            ForEach(0..<50) { _ in
                Text("Hello World")
                    .padding()
            }
            
            VStack {
                Button {
                    show.toggle()
                } label: {
                    Text(text)
                }
            }
        }
        .clipped()

    }
}

```

```
struct TabsView: View {
    
    @State var show = false
    
    var body: some View {
        
        ZStack {
            TabView {
                ChildView(show: $show, text: "FirstView")
                    .tabItem({
                        Label("First", systemImage: "greetingcard")
                    })
            }
        }
        .popup(isPresented: $show, type: .default, dragToDismiss: true, closeOnTap: false, closeOnTapOutside: true, backgroundColor: .black.opacity(0.5)) {
            VStack {
                Text("👻")
                Text("Hello World.")
                Button {
                    show.toggle()
                } label: {
                    Text("Dismiss ")
                }
            }
            .padding(.vertical, 20)
            .padding(.horizontal, 40)
            .frame(width: 300, height: 300)
            .background(.red)
            .cornerRadius(10)
        }
    }
}

```

**Comment by f3dm76** [comment]
Hey @solkpolk, sorry for the slow answer. I'm happy to say, I fixed the issue. I added my fix to version 1.0.4, you are most welcome to give it a go. Have a marvellous day!

**Comment by alex2015** [comment]
Hello @f3dm76 the problem not fixed. Please  fix this problem. Without solving this problem, I can't use the library. It becomes useless!

**Comment by f3dm76** [comment]
Try 1.0.5

**Comment by alex2015** [comment]
@f3dm76 Thank you. It works. Issue is fixed.
